version: "3"
volumes:
  data-volume: {}
services:
  redis:
    image: redis:alpine
    container_name: redis_go2
    expose:
      - "6379"
  db:
    container_name: mysql_go
    build: ./db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 3308:3306
    volumes:
      - data-volume:/var/lib/mysql
      - ./db/api_queue.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_queue
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  app:
    build: .
    command: npm run go
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
        - REDIS_URL=redis://redis_go2:6379
        - DB_HOST=db
        - BD_PORT=3308
        - DB_DATABASE=api_queue
        - DB_USERNAME=root
        - DB_PASSWORD=root
networks:
  my_net:

